// Mocks generated by Mockito 5.4.6 from annotations
// in shadow_app/test/unit/domain/usecases/guest_invites/guest_invite_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:shadow_app/core/errors/app_error.dart' as _i6;
import 'package:shadow_app/core/types/result.dart' as _i4;
import 'package:shadow_app/domain/entities/guest_invite.dart' as _i5;
import 'package:shadow_app/domain/repositories/guest_invite_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GuestInviteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGuestInviteRepository extends _i1.Mock
    implements _i2.GuestInviteRepository {
  MockGuestInviteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.GuestInvite, _i6.AppError>> create(
    _i5.GuestInvite? invite,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [invite]),
            returnValue:
                _i3.Future<_i4.Result<_i5.GuestInvite, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i5.GuestInvite, _i6.AppError>>(
                    this,
                    Invocation.method(#create, [invite]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.GuestInvite, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i5.GuestInvite, _i6.AppError>> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue:
                _i3.Future<_i4.Result<_i5.GuestInvite, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i5.GuestInvite, _i6.AppError>>(
                    this,
                    Invocation.method(#getById, [id]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.GuestInvite, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i5.GuestInvite?, _i6.AppError>> getByToken(
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getByToken, [token]),
            returnValue:
                _i3.Future<_i4.Result<_i5.GuestInvite?, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i5.GuestInvite?, _i6.AppError>>(
                    this,
                    Invocation.method(#getByToken, [token]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.GuestInvite?, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i5.GuestInvite>, _i6.AppError>> getByProfile(
    String? profileId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getByProfile, [profileId]),
            returnValue:
                _i3.Future<
                  _i4.Result<List<_i5.GuestInvite>, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<List<_i5.GuestInvite>, _i6.AppError>
                  >(this, Invocation.method(#getByProfile, [profileId])),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.GuestInvite>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i5.GuestInvite, _i6.AppError>> update(
    _i5.GuestInvite? invite,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [invite]),
            returnValue:
                _i3.Future<_i4.Result<_i5.GuestInvite, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i5.GuestInvite, _i6.AppError>>(
                    this,
                    Invocation.method(#update, [invite]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.GuestInvite, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> revoke(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#revoke, [id]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#revoke, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> hardDelete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#hardDelete, [id]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#hardDelete, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);
}
