// Mocks generated by Mockito 5.4.6 from annotations
// in shadow_app/test/unit/domain/usecases/bodily_output/get_bodily_outputs_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:shadow_app/core/errors/app_error.dart' as _i5;
import 'package:shadow_app/core/types/result.dart' as _i4;
import 'package:shadow_app/domain/entities/bodily_output_enums.dart' as _i8;
import 'package:shadow_app/domain/entities/bodily_output_log.dart' as _i6;
import 'package:shadow_app/domain/repositories/bodily_output_repository.dart'
    as _i2;
import 'package:shadow_app/domain/services/profile_authorization_service.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BodilyOutputRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBodilyOutputRepository extends _i1.Mock
    implements _i2.BodilyOutputRepository {
  MockBodilyOutputRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<void, _i5.AppError>> log(_i6.BodilyOutputLog? entry) =>
      (super.noSuchMethod(
            Invocation.method(#log, [entry]),
            returnValue: _i3.Future<_i4.Result<void, _i5.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i5.AppError>>(
                this,
                Invocation.method(#log, [entry]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i5.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i6.BodilyOutputLog>, _i5.AppError>> getAll(
    String? profileId, {
    int? from,
    int? to,
    _i8.BodyOutputType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getAll,
              [profileId],
              {#from: from, #to: to, #type: type},
            ),
            returnValue:
                _i3.Future<
                  _i4.Result<List<_i6.BodilyOutputLog>, _i5.AppError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<List<_i6.BodilyOutputLog>, _i5.AppError>
                  >(
                    this,
                    Invocation.method(
                      #getAll,
                      [profileId],
                      {#from: from, #to: to, #type: type},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i6.BodilyOutputLog>, _i5.AppError>>);

  @override
  _i3.Future<_i4.Result<_i6.BodilyOutputLog, _i5.AppError>> getById(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue:
                _i3.Future<_i4.Result<_i6.BodilyOutputLog, _i5.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i6.BodilyOutputLog, _i5.AppError>>(
                    this,
                    Invocation.method(#getById, [id]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i6.BodilyOutputLog, _i5.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i5.AppError>> update(
    _i6.BodilyOutputLog? entry,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [entry]),
            returnValue: _i3.Future<_i4.Result<void, _i5.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i5.AppError>>(
                this,
                Invocation.method(#update, [entry]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i5.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i5.AppError>> delete(
    String? profileId,
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [profileId, id]),
            returnValue: _i3.Future<_i4.Result<void, _i5.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i5.AppError>>(
                this,
                Invocation.method(#delete, [profileId, id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i5.AppError>>);
}

/// A class which mocks [ProfileAuthorizationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileAuthorizationService extends _i1.Mock
    implements _i9.ProfileAuthorizationService {
  MockProfileAuthorizationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> canRead(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#canRead, [profileId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> canWrite(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#canWrite, [profileId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> isOwner(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#isOwner, [profileId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i9.ProfileAccess>> getAccessibleProfiles() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessibleProfiles, []),
            returnValue: _i3.Future<List<_i9.ProfileAccess>>.value(
              <_i9.ProfileAccess>[],
            ),
          )
          as _i3.Future<List<_i9.ProfileAccess>>);
}
