// Mocks generated by Mockito 5.4.6 from annotations
// in shadow_app/test/unit/domain/usecases/diet/diet_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:shadow_app/core/errors/app_error.dart' as _i6;
import 'package:shadow_app/core/types/result.dart' as _i4;
import 'package:shadow_app/domain/entities/diet.dart' as _i5;
import 'package:shadow_app/domain/entities/diet_exception.dart' as _i9;
import 'package:shadow_app/domain/entities/diet_rule.dart' as _i8;
import 'package:shadow_app/domain/entities/diet_violation.dart' as _i11;
import 'package:shadow_app/domain/entities/food_item.dart' as _i13;
import 'package:shadow_app/domain/entities/food_item_component.dart' as _i15;
import 'package:shadow_app/domain/enums/health_enums.dart' as _i14;
import 'package:shadow_app/domain/repositories/diet_repository.dart' as _i2;
import 'package:shadow_app/domain/repositories/diet_violation_repository.dart'
    as _i10;
import 'package:shadow_app/domain/repositories/food_item_repository.dart'
    as _i12;
import 'package:shadow_app/domain/services/diet_compliance_service.dart'
    as _i16;
import 'package:shadow_app/domain/services/profile_authorization_service.dart'
    as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DietRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDietRepository extends _i1.Mock implements _i2.DietRepository {
  MockDietRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.Diet>, _i6.AppError>> getByProfile(
    String? profileId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getByProfile, [profileId]),
            returnValue:
                _i3.Future<_i4.Result<List<_i5.Diet>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i5.Diet>, _i6.AppError>>(
                    this,
                    Invocation.method(#getByProfile, [profileId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.Diet>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i5.Diet?, _i6.AppError>> getActiveDiet(
    String? profileId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveDiet, [profileId]),
            returnValue: _i3.Future<_i4.Result<_i5.Diet?, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<_i5.Diet?, _i6.AppError>>(
                this,
                Invocation.method(#getActiveDiet, [profileId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Diet?, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i5.Diet, _i6.AppError>> setActive(
    String? dietId,
    String? profileId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setActive, [dietId, profileId]),
            returnValue: _i3.Future<_i4.Result<_i5.Diet, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<_i5.Diet, _i6.AppError>>(
                this,
                Invocation.method(#setActive, [dietId, profileId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Diet, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> deactivate(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#deactivate, [profileId]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#deactivate, [profileId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i8.DietRule>, _i6.AppError>> getRules(
    String? dietId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRules, [dietId]),
            returnValue:
                _i3.Future<_i4.Result<List<_i8.DietRule>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i8.DietRule>, _i6.AppError>>(
                    this,
                    Invocation.method(#getRules, [dietId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i8.DietRule>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i8.DietRule, _i6.AppError>> addRule(
    _i8.DietRule? rule,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addRule, [rule]),
            returnValue:
                _i3.Future<_i4.Result<_i8.DietRule, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i8.DietRule, _i6.AppError>>(
                    this,
                    Invocation.method(#addRule, [rule]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i8.DietRule, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i8.DietRule, _i6.AppError>> updateRule(
    _i8.DietRule? rule,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateRule, [rule]),
            returnValue:
                _i3.Future<_i4.Result<_i8.DietRule, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i8.DietRule, _i6.AppError>>(
                    this,
                    Invocation.method(#updateRule, [rule]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i8.DietRule, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> deleteRule(String? ruleId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRule, [ruleId]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#deleteRule, [ruleId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i9.DietException>, _i6.AppError>> getExceptions(
    String? ruleId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExceptions, [ruleId]),
            returnValue:
                _i3.Future<
                  _i4.Result<List<_i9.DietException>, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<List<_i9.DietException>, _i6.AppError>
                  >(this, Invocation.method(#getExceptions, [ruleId])),
                ),
          )
          as _i3.Future<_i4.Result<List<_i9.DietException>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i9.DietException, _i6.AppError>> addException(
    _i9.DietException? exception,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addException, [exception]),
            returnValue:
                _i3.Future<_i4.Result<_i9.DietException, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i9.DietException, _i6.AppError>>(
                    this,
                    Invocation.method(#addException, [exception]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i9.DietException, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> deleteException(
    String? exceptionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteException, [exceptionId]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#deleteException, [exceptionId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Diet>, _i6.AppError>> getAll({
    String? profileId,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {
              #profileId: profileId,
              #limit: limit,
              #offset: offset,
            }),
            returnValue:
                _i3.Future<_i4.Result<List<_i5.Diet>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i5.Diet>, _i6.AppError>>(
                    this,
                    Invocation.method(#getAll, [], {
                      #profileId: profileId,
                      #limit: limit,
                      #offset: offset,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.Diet>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i5.Diet, _i6.AppError>> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i3.Future<_i4.Result<_i5.Diet, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<_i5.Diet, _i6.AppError>>(
                this,
                Invocation.method(#getById, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Diet, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i5.Diet, _i6.AppError>> create(_i5.Diet? entity) =>
      (super.noSuchMethod(
            Invocation.method(#create, [entity]),
            returnValue: _i3.Future<_i4.Result<_i5.Diet, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<_i5.Diet, _i6.AppError>>(
                this,
                Invocation.method(#create, [entity]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Diet, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i5.Diet, _i6.AppError>> update(
    _i5.Diet? entity, {
    bool? markDirty = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update, [entity], {#markDirty: markDirty}),
            returnValue: _i3.Future<_i4.Result<_i5.Diet, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<_i5.Diet, _i6.AppError>>(
                this,
                Invocation.method(#update, [entity], {#markDirty: markDirty}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Diet, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#delete, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> hardDelete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#hardDelete, [id]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#hardDelete, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Diet>, _i6.AppError>> getModifiedSince(
    int? since,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getModifiedSince, [since]),
            returnValue:
                _i3.Future<_i4.Result<List<_i5.Diet>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i5.Diet>, _i6.AppError>>(
                    this,
                    Invocation.method(#getModifiedSince, [since]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.Diet>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Diet>, _i6.AppError>> getPendingSync() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSync, []),
            returnValue:
                _i3.Future<_i4.Result<List<_i5.Diet>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i5.Diet>, _i6.AppError>>(
                    this,
                    Invocation.method(#getPendingSync, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.Diet>, _i6.AppError>>);
}

/// A class which mocks [DietViolationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDietViolationRepository extends _i1.Mock
    implements _i10.DietViolationRepository {
  MockDietViolationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i11.DietViolation>, _i6.AppError>> getByProfile(
    String? profileId, {
    int? startDate,
    int? endDate,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getByProfile,
              [profileId],
              {#startDate: startDate, #endDate: endDate, #limit: limit},
            ),
            returnValue:
                _i3.Future<
                  _i4.Result<List<_i11.DietViolation>, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<List<_i11.DietViolation>, _i6.AppError>
                  >(
                    this,
                    Invocation.method(
                      #getByProfile,
                      [profileId],
                      {#startDate: startDate, #endDate: endDate, #limit: limit},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i11.DietViolation>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i11.DietViolation>, _i6.AppError>> getByDiet(
    String? dietId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getByDiet, [dietId]),
            returnValue:
                _i3.Future<
                  _i4.Result<List<_i11.DietViolation>, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<List<_i11.DietViolation>, _i6.AppError>
                  >(this, Invocation.method(#getByDiet, [dietId])),
                ),
          )
          as _i3.Future<_i4.Result<List<_i11.DietViolation>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i11.DietViolation>, _i6.AppError>> getAll({
    String? profileId,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {
              #profileId: profileId,
              #limit: limit,
              #offset: offset,
            }),
            returnValue:
                _i3.Future<
                  _i4.Result<List<_i11.DietViolation>, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<List<_i11.DietViolation>, _i6.AppError>
                  >(
                    this,
                    Invocation.method(#getAll, [], {
                      #profileId: profileId,
                      #limit: limit,
                      #offset: offset,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i11.DietViolation>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i11.DietViolation, _i6.AppError>> getById(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue:
                _i3.Future<_i4.Result<_i11.DietViolation, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i11.DietViolation, _i6.AppError>>(
                    this,
                    Invocation.method(#getById, [id]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i11.DietViolation, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i11.DietViolation, _i6.AppError>> create(
    _i11.DietViolation? entity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [entity]),
            returnValue:
                _i3.Future<_i4.Result<_i11.DietViolation, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i11.DietViolation, _i6.AppError>>(
                    this,
                    Invocation.method(#create, [entity]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i11.DietViolation, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i11.DietViolation, _i6.AppError>> update(
    _i11.DietViolation? entity, {
    bool? markDirty = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update, [entity], {#markDirty: markDirty}),
            returnValue:
                _i3.Future<_i4.Result<_i11.DietViolation, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i11.DietViolation, _i6.AppError>>(
                    this,
                    Invocation.method(
                      #update,
                      [entity],
                      {#markDirty: markDirty},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i11.DietViolation, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#delete, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> hardDelete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#hardDelete, [id]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#hardDelete, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i11.DietViolation>, _i6.AppError>>
  getModifiedSince(int? since) =>
      (super.noSuchMethod(
            Invocation.method(#getModifiedSince, [since]),
            returnValue:
                _i3.Future<
                  _i4.Result<List<_i11.DietViolation>, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<List<_i11.DietViolation>, _i6.AppError>
                  >(this, Invocation.method(#getModifiedSince, [since])),
                ),
          )
          as _i3.Future<_i4.Result<List<_i11.DietViolation>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i11.DietViolation>, _i6.AppError>>
  getPendingSync() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSync, []),
            returnValue:
                _i3.Future<
                  _i4.Result<List<_i11.DietViolation>, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<List<_i11.DietViolation>, _i6.AppError>
                  >(this, Invocation.method(#getPendingSync, [])),
                ),
          )
          as _i3.Future<_i4.Result<List<_i11.DietViolation>, _i6.AppError>>);
}

/// A class which mocks [FoodItemRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoodItemRepository extends _i1.Mock
    implements _i12.FoodItemRepository {
  MockFoodItemRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i13.FoodItem>, _i6.AppError>> getByProfile(
    String? profileId, {
    _i14.FoodItemType? type,
    bool? includeArchived = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getByProfile,
              [profileId],
              {#type: type, #includeArchived: includeArchived},
            ),
            returnValue:
                _i3.Future<_i4.Result<List<_i13.FoodItem>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i13.FoodItem>, _i6.AppError>>(
                    this,
                    Invocation.method(
                      #getByProfile,
                      [profileId],
                      {#type: type, #includeArchived: includeArchived},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i13.FoodItem>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i13.FoodItem>, _i6.AppError>> search(
    String? profileId,
    String? query, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#search, [profileId, query], {#limit: limit}),
            returnValue:
                _i3.Future<_i4.Result<List<_i13.FoodItem>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i13.FoodItem>, _i6.AppError>>(
                    this,
                    Invocation.method(
                      #search,
                      [profileId, query],
                      {#limit: limit},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i13.FoodItem>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> archive(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#archive, [id]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#archive, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i13.FoodItem>, _i6.AppError>>
  searchExcludingCategories(
    String? profileId,
    String? query, {
    required List<String>? excludeCategories,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchExcludingCategories,
              [profileId, query],
              {#excludeCategories: excludeCategories, #limit: limit},
            ),
            returnValue:
                _i3.Future<_i4.Result<List<_i13.FoodItem>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i13.FoodItem>, _i6.AppError>>(
                    this,
                    Invocation.method(
                      #searchExcludingCategories,
                      [profileId, query],
                      {#excludeCategories: excludeCategories, #limit: limit},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i13.FoodItem>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i15.FoodItemComponent>, _i6.AppError>>
  getComponents(String? composedFoodItemId) =>
      (super.noSuchMethod(
            Invocation.method(#getComponents, [composedFoodItemId]),
            returnValue:
                _i3.Future<
                  _i4.Result<List<_i15.FoodItemComponent>, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<List<_i15.FoodItemComponent>, _i6.AppError>
                  >(
                    this,
                    Invocation.method(#getComponents, [composedFoodItemId]),
                  ),
                ),
          )
          as _i3.Future<
            _i4.Result<List<_i15.FoodItemComponent>, _i6.AppError>
          >);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> replaceComponents(
    String? composedFoodItemId,
    List<_i15.FoodItemComponent>? components,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#replaceComponents, [
              composedFoodItemId,
              components,
            ]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#replaceComponents, [
                  composedFoodItemId,
                  components,
                ]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> deleteComponents(
    String? composedFoodItemId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteComponents, [composedFoodItemId]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#deleteComponents, [composedFoodItemId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i13.FoodItem>, _i6.AppError>> getAll({
    String? profileId,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {
              #profileId: profileId,
              #limit: limit,
              #offset: offset,
            }),
            returnValue:
                _i3.Future<_i4.Result<List<_i13.FoodItem>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i13.FoodItem>, _i6.AppError>>(
                    this,
                    Invocation.method(#getAll, [], {
                      #profileId: profileId,
                      #limit: limit,
                      #offset: offset,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i13.FoodItem>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i13.FoodItem, _i6.AppError>> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue:
                _i3.Future<_i4.Result<_i13.FoodItem, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i13.FoodItem, _i6.AppError>>(
                    this,
                    Invocation.method(#getById, [id]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i13.FoodItem, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i13.FoodItem, _i6.AppError>> create(
    _i13.FoodItem? entity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [entity]),
            returnValue:
                _i3.Future<_i4.Result<_i13.FoodItem, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i13.FoodItem, _i6.AppError>>(
                    this,
                    Invocation.method(#create, [entity]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i13.FoodItem, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i13.FoodItem, _i6.AppError>> update(
    _i13.FoodItem? entity, {
    bool? markDirty = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update, [entity], {#markDirty: markDirty}),
            returnValue:
                _i3.Future<_i4.Result<_i13.FoodItem, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i13.FoodItem, _i6.AppError>>(
                    this,
                    Invocation.method(
                      #update,
                      [entity],
                      {#markDirty: markDirty},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i13.FoodItem, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#delete, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> hardDelete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#hardDelete, [id]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#hardDelete, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i13.FoodItem>, _i6.AppError>> getModifiedSince(
    int? since,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getModifiedSince, [since]),
            returnValue:
                _i3.Future<_i4.Result<List<_i13.FoodItem>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i13.FoodItem>, _i6.AppError>>(
                    this,
                    Invocation.method(#getModifiedSince, [since]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i13.FoodItem>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i13.FoodItem>, _i6.AppError>> getPendingSync() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSync, []),
            returnValue:
                _i3.Future<_i4.Result<List<_i13.FoodItem>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i13.FoodItem>, _i6.AppError>>(
                    this,
                    Invocation.method(#getPendingSync, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i13.FoodItem>, _i6.AppError>>);
}

/// A class which mocks [DietComplianceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDietComplianceService extends _i1.Mock
    implements _i16.DietComplianceService {
  MockDietComplianceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i8.DietRule> checkFoodAgainstRules(
    _i13.FoodItem? food,
    List<_i8.DietRule>? rules,
    int? logTimeEpoch,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkFoodAgainstRules, [
              food,
              rules,
              logTimeEpoch,
            ]),
            returnValue: <_i8.DietRule>[],
          )
          as List<_i8.DietRule>);

  @override
  double calculateImpact(String? profileId, List<_i8.DietRule>? violations) =>
      (super.noSuchMethod(
            Invocation.method(#calculateImpact, [profileId, violations]),
            returnValue: 0.0,
          )
          as double);
}

/// A class which mocks [ProfileAuthorizationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileAuthorizationService extends _i1.Mock
    implements _i17.ProfileAuthorizationService {
  MockProfileAuthorizationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> canRead(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#canRead, [profileId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> canWrite(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#canWrite, [profileId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> isOwner(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#isOwner, [profileId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i17.ProfileAccess>> getAccessibleProfiles() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessibleProfiles, []),
            returnValue: _i3.Future<List<_i17.ProfileAccess>>.value(
              <_i17.ProfileAccess>[],
            ),
          )
          as _i3.Future<List<_i17.ProfileAccess>>);
}
