// Mocks generated by Mockito 5.4.6 from annotations
// in shadow_app/test/unit/data/services/sync_service_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:shadow_app/core/errors/app_error.dart' as _i6;
import 'package:shadow_app/core/services/encryption_service.dart' as _i8;
import 'package:shadow_app/core/types/result.dart' as _i4;
import 'package:shadow_app/data/datasources/remote/cloud_storage_provider.dart'
    as _i10;
import 'package:shadow_app/domain/entities/supplement.dart' as _i5;
import 'package:shadow_app/domain/repositories/supplement_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SupplementRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupplementRepository extends _i1.Mock
    implements _i2.SupplementRepository {
  MockSupplementRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.Supplement>, _i6.AppError>> getByProfile(
    String? profileId, {
    bool? activeOnly,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getByProfile,
              [profileId],
              {#activeOnly: activeOnly, #limit: limit, #offset: offset},
            ),
            returnValue:
                _i3.Future<
                  _i4.Result<List<_i5.Supplement>, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<List<_i5.Supplement>, _i6.AppError>
                  >(
                    this,
                    Invocation.method(
                      #getByProfile,
                      [profileId],
                      {#activeOnly: activeOnly, #limit: limit, #offset: offset},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.Supplement>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Supplement>, _i6.AppError>> getDueAt(
    String? profileId,
    int? time,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDueAt, [profileId, time]),
            returnValue:
                _i3.Future<
                  _i4.Result<List<_i5.Supplement>, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<List<_i5.Supplement>, _i6.AppError>
                  >(this, Invocation.method(#getDueAt, [profileId, time])),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.Supplement>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Supplement>, _i6.AppError>> search(
    String? profileId,
    String? query, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#search, [profileId, query], {#limit: limit}),
            returnValue:
                _i3.Future<
                  _i4.Result<List<_i5.Supplement>, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<List<_i5.Supplement>, _i6.AppError>
                  >(
                    this,
                    Invocation.method(
                      #search,
                      [profileId, query],
                      {#limit: limit},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.Supplement>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Supplement>, _i6.AppError>> getAll({
    String? profileId,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {
              #profileId: profileId,
              #limit: limit,
              #offset: offset,
            }),
            returnValue:
                _i3.Future<
                  _i4.Result<List<_i5.Supplement>, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<List<_i5.Supplement>, _i6.AppError>
                  >(
                    this,
                    Invocation.method(#getAll, [], {
                      #profileId: profileId,
                      #limit: limit,
                      #offset: offset,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.Supplement>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i5.Supplement, _i6.AppError>> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue:
                _i3.Future<_i4.Result<_i5.Supplement, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i5.Supplement, _i6.AppError>>(
                    this,
                    Invocation.method(#getById, [id]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.Supplement, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i5.Supplement, _i6.AppError>> create(
    _i5.Supplement? entity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [entity]),
            returnValue:
                _i3.Future<_i4.Result<_i5.Supplement, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i5.Supplement, _i6.AppError>>(
                    this,
                    Invocation.method(#create, [entity]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.Supplement, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i5.Supplement, _i6.AppError>> update(
    _i5.Supplement? entity, {
    bool? markDirty = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update, [entity], {#markDirty: markDirty}),
            returnValue:
                _i3.Future<_i4.Result<_i5.Supplement, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i5.Supplement, _i6.AppError>>(
                    this,
                    Invocation.method(
                      #update,
                      [entity],
                      {#markDirty: markDirty},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.Supplement, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#delete, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> hardDelete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#hardDelete, [id]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#hardDelete, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Supplement>, _i6.AppError>> getModifiedSince(
    int? since,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getModifiedSince, [since]),
            returnValue:
                _i3.Future<
                  _i4.Result<List<_i5.Supplement>, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<List<_i5.Supplement>, _i6.AppError>
                  >(this, Invocation.method(#getModifiedSince, [since])),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.Supplement>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Supplement>, _i6.AppError>> getPendingSync() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSync, []),
            returnValue:
                _i3.Future<
                  _i4.Result<List<_i5.Supplement>, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<List<_i5.Supplement>, _i6.AppError>
                  >(this, Invocation.method(#getPendingSync, [])),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.Supplement>, _i6.AppError>>);
}

/// A class which mocks [EncryptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEncryptionService extends _i1.Mock implements _i8.EncryptionService {
  MockEncryptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i9.Uint8List generateKey() =>
      (super.noSuchMethod(
            Invocation.method(#generateKey, []),
            returnValue: _i9.Uint8List(0),
          )
          as _i9.Uint8List);

  @override
  _i3.Future<String> encrypt(String? plaintext) =>
      (super.noSuchMethod(
            Invocation.method(#encrypt, [plaintext]),
            returnValue: _i3.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#encrypt, [plaintext]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> decrypt(String? encrypted) =>
      (super.noSuchMethod(
            Invocation.method(#decrypt, [encrypted]),
            returnValue: _i3.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#decrypt, [encrypted]),
              ),
            ),
          )
          as _i3.Future<String>);
}

/// A class which mocks [CloudStorageProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCloudStorageProvider extends _i1.Mock
    implements _i10.CloudStorageProvider {
  MockCloudStorageProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.CloudProviderType get providerType =>
      (super.noSuchMethod(
            Invocation.getter(#providerType),
            returnValue: _i10.CloudProviderType.googleDrive,
          )
          as _i10.CloudProviderType);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> authenticate() =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, []),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#authenticate, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> isAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isAvailable, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> uploadEntity(
    String? entityType,
    String? entityId,
    String? profileId,
    String? clientId,
    Map<String, dynamic>? json,
    int? version,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadEntity, [
              entityType,
              entityId,
              profileId,
              clientId,
              json,
              version,
            ]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#uploadEntity, [
                  entityType,
                  entityId,
                  profileId,
                  clientId,
                  json,
                  version,
                ]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<Map<String, dynamic>?, _i6.AppError>> downloadEntity(
    String? entityType,
    String? entityId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#downloadEntity, [entityType, entityId]),
            returnValue:
                _i3.Future<
                  _i4.Result<Map<String, dynamic>?, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<Map<String, dynamic>?, _i6.AppError>
                  >(
                    this,
                    Invocation.method(#downloadEntity, [entityType, entityId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<Map<String, dynamic>?, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i10.SyncChange>, _i6.AppError>> getChangesSince(
    int? sinceTimestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getChangesSince, [sinceTimestamp]),
            returnValue:
                _i3.Future<
                  _i4.Result<List<_i10.SyncChange>, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<List<_i10.SyncChange>, _i6.AppError>
                  >(
                    this,
                    Invocation.method(#getChangesSince, [sinceTimestamp]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i10.SyncChange>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> deleteEntity(
    String? entityType,
    String? entityId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEntity, [entityType, entityId]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#deleteEntity, [entityType, entityId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> uploadFile(
    String? localPath,
    String? remotePath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFile, [localPath, remotePath]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#uploadFile, [localPath, remotePath]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<String, _i6.AppError>> downloadFile(
    String? remotePath,
    String? localPath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#downloadFile, [remotePath, localPath]),
            returnValue: _i3.Future<_i4.Result<String, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<String, _i6.AppError>>(
                this,
                Invocation.method(#downloadFile, [remotePath, localPath]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<String, _i6.AppError>>);
}
