// Mocks generated by Mockito 5.4.6 from annotations
// in shadow_app/test/unit/domain/usecases/notifications/notification_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:shadow_app/core/errors/app_error.dart' as _i6;
import 'package:shadow_app/core/types/result.dart' as _i4;
import 'package:shadow_app/domain/entities/anchor_event_time.dart' as _i5;
import 'package:shadow_app/domain/entities/notification_category_settings.dart'
    as _i10;
import 'package:shadow_app/domain/enums/notification_enums.dart' as _i8;
import 'package:shadow_app/domain/repositories/anchor_event_time_repository.dart'
    as _i2;
import 'package:shadow_app/domain/repositories/notification_category_settings_repository.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AnchorEventTimeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnchorEventTimeRepository extends _i1.Mock
    implements _i2.AnchorEventTimeRepository {
  MockAnchorEventTimeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.AnchorEventTime>, _i6.AppError>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue:
                _i3.Future<
                  _i4.Result<List<_i5.AnchorEventTime>, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<List<_i5.AnchorEventTime>, _i6.AppError>
                  >(this, Invocation.method(#getAll, [])),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.AnchorEventTime>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i5.AnchorEventTime?, _i6.AppError>> getByName(
    _i8.AnchorEventName? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getByName, [name]),
            returnValue:
                _i3.Future<
                  _i4.Result<_i5.AnchorEventTime?, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<_i5.AnchorEventTime?, _i6.AppError>
                  >(this, Invocation.method(#getByName, [name])),
                ),
          )
          as _i3.Future<_i4.Result<_i5.AnchorEventTime?, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i5.AnchorEventTime, _i6.AppError>> getById(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue:
                _i3.Future<_i4.Result<_i5.AnchorEventTime, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i5.AnchorEventTime, _i6.AppError>>(
                    this,
                    Invocation.method(#getById, [id]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.AnchorEventTime, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i5.AnchorEventTime, _i6.AppError>> create(
    _i5.AnchorEventTime? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue:
                _i3.Future<_i4.Result<_i5.AnchorEventTime, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i5.AnchorEventTime, _i6.AppError>>(
                    this,
                    Invocation.method(#create, [event]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.AnchorEventTime, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i5.AnchorEventTime, _i6.AppError>> update(
    _i5.AnchorEventTime? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue:
                _i3.Future<_i4.Result<_i5.AnchorEventTime, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i5.AnchorEventTime, _i6.AppError>>(
                    this,
                    Invocation.method(#update, [event]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.AnchorEventTime, _i6.AppError>>);
}

/// A class which mocks [NotificationCategorySettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationCategorySettingsRepository extends _i1.Mock
    implements _i9.NotificationCategorySettingsRepository {
  MockNotificationCategorySettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i10.NotificationCategorySettings>, _i6.AppError>>
  getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue:
                _i3.Future<
                  _i4.Result<
                    List<_i10.NotificationCategorySettings>,
                    _i6.AppError
                  >
                >.value(
                  _i7.dummyValue<
                    _i4.Result<
                      List<_i10.NotificationCategorySettings>,
                      _i6.AppError
                    >
                  >(this, Invocation.method(#getAll, [])),
                ),
          )
          as _i3.Future<
            _i4.Result<List<_i10.NotificationCategorySettings>, _i6.AppError>
          >);

  @override
  _i3.Future<_i4.Result<_i10.NotificationCategorySettings?, _i6.AppError>>
  getByCategory(_i8.NotificationCategory? category) =>
      (super.noSuchMethod(
            Invocation.method(#getByCategory, [category]),
            returnValue:
                _i3.Future<
                  _i4.Result<_i10.NotificationCategorySettings?, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<_i10.NotificationCategorySettings?, _i6.AppError>
                  >(this, Invocation.method(#getByCategory, [category])),
                ),
          )
          as _i3.Future<
            _i4.Result<_i10.NotificationCategorySettings?, _i6.AppError>
          >);

  @override
  _i3.Future<_i4.Result<_i10.NotificationCategorySettings, _i6.AppError>>
  getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue:
                _i3.Future<
                  _i4.Result<_i10.NotificationCategorySettings, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<_i10.NotificationCategorySettings, _i6.AppError>
                  >(this, Invocation.method(#getById, [id])),
                ),
          )
          as _i3.Future<
            _i4.Result<_i10.NotificationCategorySettings, _i6.AppError>
          >);

  @override
  _i3.Future<_i4.Result<_i10.NotificationCategorySettings, _i6.AppError>>
  create(_i10.NotificationCategorySettings? settings) =>
      (super.noSuchMethod(
            Invocation.method(#create, [settings]),
            returnValue:
                _i3.Future<
                  _i4.Result<_i10.NotificationCategorySettings, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<_i10.NotificationCategorySettings, _i6.AppError>
                  >(this, Invocation.method(#create, [settings])),
                ),
          )
          as _i3.Future<
            _i4.Result<_i10.NotificationCategorySettings, _i6.AppError>
          >);

  @override
  _i3.Future<_i4.Result<_i10.NotificationCategorySettings, _i6.AppError>>
  update(_i10.NotificationCategorySettings? settings) =>
      (super.noSuchMethod(
            Invocation.method(#update, [settings]),
            returnValue:
                _i3.Future<
                  _i4.Result<_i10.NotificationCategorySettings, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<_i10.NotificationCategorySettings, _i6.AppError>
                  >(this, Invocation.method(#update, [settings])),
                ),
          )
          as _i3.Future<
            _i4.Result<_i10.NotificationCategorySettings, _i6.AppError>
          >);
}
