// Mocks generated by Mockito 5.4.6 from annotations
// in shadow_app/test/unit/data/cloud/icloud_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:icloud_storage/icloud_storage.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shadow_app/data/cloud/icloud_provider.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ICloudStorageWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockICloudStorageWrapper extends _i1.Mock
    implements _i2.ICloudStorageWrapper {
  MockICloudStorageWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ICloudFile>> gather({required String? containerId}) =>
      (super.noSuchMethod(
            Invocation.method(#gather, [], {#containerId: containerId}),
            returnValue: _i3.Future<List<_i4.ICloudFile>>.value(
              <_i4.ICloudFile>[],
            ),
          )
          as _i3.Future<List<_i4.ICloudFile>>);

  @override
  _i3.Future<void> upload({
    required String? containerId,
    required String? filePath,
    required String? destinationRelativePath,
    dynamic onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upload, [], {
              #containerId: containerId,
              #filePath: filePath,
              #destinationRelativePath: destinationRelativePath,
              #onProgress: onProgress,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> download({
    required String? containerId,
    required String? relativePath,
    required String? destinationFilePath,
    dynamic onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#download, [], {
              #containerId: containerId,
              #relativePath: relativePath,
              #destinationFilePath: destinationFilePath,
              #onProgress: onProgress,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> delete({
    required String? containerId,
    required String? relativePath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #containerId: containerId,
              #relativePath: relativePath,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
