// Mocks generated by Mockito 5.4.6 from annotations
// in shadow_app/test/unit/domain/usecases/health/sync_from_health_platform_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:shadow_app/core/errors/app_error.dart' as _i6;
import 'package:shadow_app/core/types/result.dart' as _i5;
import 'package:shadow_app/domain/entities/health_sync_settings.dart' as _i9;
import 'package:shadow_app/domain/entities/health_sync_status.dart' as _i11;
import 'package:shadow_app/domain/entities/imported_vital.dart' as _i13;
import 'package:shadow_app/domain/enums/health_enums.dart' as _i3;
import 'package:shadow_app/domain/repositories/health_platform_service.dart'
    as _i2;
import 'package:shadow_app/domain/repositories/health_sync_settings_repository.dart'
    as _i8;
import 'package:shadow_app/domain/repositories/health_sync_status_repository.dart'
    as _i10;
import 'package:shadow_app/domain/repositories/imported_vital_repository.dart'
    as _i12;
import 'package:shadow_app/domain/services/profile_authorization_service.dart'
    as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HealthPlatformService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHealthPlatformService extends _i1.Mock
    implements _i2.HealthPlatformService {
  MockHealthPlatformService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.HealthSourcePlatform get currentPlatform =>
      (super.noSuchMethod(
            Invocation.getter(#currentPlatform),
            returnValue: _i3.HealthSourcePlatform.appleHealth,
          )
          as _i3.HealthSourcePlatform);

  @override
  _i4.Future<bool> isAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isAvailable, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i5.Result<List<_i3.HealthDataType>, _i6.AppError>>
  requestPermissions(List<_i3.HealthDataType>? types) =>
      (super.noSuchMethod(
            Invocation.method(#requestPermissions, [types]),
            returnValue:
                _i4.Future<
                  _i5.Result<List<_i3.HealthDataType>, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i5.Result<List<_i3.HealthDataType>, _i6.AppError>
                  >(this, Invocation.method(#requestPermissions, [types])),
                ),
          )
          as _i4.Future<_i5.Result<List<_i3.HealthDataType>, _i6.AppError>>);

  @override
  _i4.Future<_i5.Result<List<_i2.HealthDataRecord>, _i6.AppError>> readRecords(
    _i3.HealthDataType? dataType,
    int? sinceEpochMs,
    int? untilEpochMs,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readRecords, [
              dataType,
              sinceEpochMs,
              untilEpochMs,
            ]),
            returnValue:
                _i4.Future<
                  _i5.Result<List<_i2.HealthDataRecord>, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i5.Result<List<_i2.HealthDataRecord>, _i6.AppError>
                  >(
                    this,
                    Invocation.method(#readRecords, [
                      dataType,
                      sinceEpochMs,
                      untilEpochMs,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<List<_i2.HealthDataRecord>, _i6.AppError>>);
}

/// A class which mocks [HealthSyncSettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHealthSyncSettingsRepository extends _i1.Mock
    implements _i8.HealthSyncSettingsRepository {
  MockHealthSyncSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Result<_i9.HealthSyncSettings?, _i6.AppError>> getByProfile(
    String? profileId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getByProfile, [profileId]),
            returnValue:
                _i4.Future<
                  _i5.Result<_i9.HealthSyncSettings?, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i5.Result<_i9.HealthSyncSettings?, _i6.AppError>
                  >(this, Invocation.method(#getByProfile, [profileId])),
                ),
          )
          as _i4.Future<_i5.Result<_i9.HealthSyncSettings?, _i6.AppError>>);

  @override
  _i4.Future<_i5.Result<_i9.HealthSyncSettings, _i6.AppError>> save(
    _i9.HealthSyncSettings? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#save, [settings]),
            returnValue:
                _i4.Future<
                  _i5.Result<_i9.HealthSyncSettings, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i5.Result<_i9.HealthSyncSettings, _i6.AppError>
                  >(this, Invocation.method(#save, [settings])),
                ),
          )
          as _i4.Future<_i5.Result<_i9.HealthSyncSettings, _i6.AppError>>);
}

/// A class which mocks [HealthSyncStatusRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHealthSyncStatusRepository extends _i1.Mock
    implements _i10.HealthSyncStatusRepository {
  MockHealthSyncStatusRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Result<List<_i11.HealthSyncStatus>, _i6.AppError>>
  getByProfile(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#getByProfile, [profileId]),
            returnValue:
                _i4.Future<
                  _i5.Result<List<_i11.HealthSyncStatus>, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i5.Result<List<_i11.HealthSyncStatus>, _i6.AppError>
                  >(this, Invocation.method(#getByProfile, [profileId])),
                ),
          )
          as _i4.Future<_i5.Result<List<_i11.HealthSyncStatus>, _i6.AppError>>);

  @override
  _i4.Future<_i5.Result<_i11.HealthSyncStatus?, _i6.AppError>> getByDataType(
    String? profileId,
    _i3.HealthDataType? dataType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getByDataType, [profileId, dataType]),
            returnValue:
                _i4.Future<
                  _i5.Result<_i11.HealthSyncStatus?, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i5.Result<_i11.HealthSyncStatus?, _i6.AppError>
                  >(
                    this,
                    Invocation.method(#getByDataType, [profileId, dataType]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i11.HealthSyncStatus?, _i6.AppError>>);

  @override
  _i4.Future<_i5.Result<_i11.HealthSyncStatus, _i6.AppError>> upsert(
    _i11.HealthSyncStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#upsert, [status]),
            returnValue:
                _i4.Future<
                  _i5.Result<_i11.HealthSyncStatus, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i5.Result<_i11.HealthSyncStatus, _i6.AppError>
                  >(this, Invocation.method(#upsert, [status])),
                ),
          )
          as _i4.Future<_i5.Result<_i11.HealthSyncStatus, _i6.AppError>>);
}

/// A class which mocks [ImportedVitalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockImportedVitalRepository extends _i1.Mock
    implements _i12.ImportedVitalRepository {
  MockImportedVitalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Result<List<_i13.ImportedVital>, _i6.AppError>> getByProfile({
    required String? profileId,
    int? startEpoch,
    int? endEpoch,
    _i3.HealthDataType? dataType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getByProfile, [], {
              #profileId: profileId,
              #startEpoch: startEpoch,
              #endEpoch: endEpoch,
              #dataType: dataType,
            }),
            returnValue:
                _i4.Future<
                  _i5.Result<List<_i13.ImportedVital>, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i5.Result<List<_i13.ImportedVital>, _i6.AppError>
                  >(
                    this,
                    Invocation.method(#getByProfile, [], {
                      #profileId: profileId,
                      #startEpoch: startEpoch,
                      #endEpoch: endEpoch,
                      #dataType: dataType,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<List<_i13.ImportedVital>, _i6.AppError>>);

  @override
  _i4.Future<_i5.Result<int, _i6.AppError>> importBatch(
    List<_i13.ImportedVital>? vitals,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#importBatch, [vitals]),
            returnValue: _i4.Future<_i5.Result<int, _i6.AppError>>.value(
              _i7.dummyValue<_i5.Result<int, _i6.AppError>>(
                this,
                Invocation.method(#importBatch, [vitals]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<int, _i6.AppError>>);

  @override
  _i4.Future<_i5.Result<int?, _i6.AppError>> getLastImportTime(
    String? profileId,
    _i3.HealthDataType? dataType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLastImportTime, [profileId, dataType]),
            returnValue: _i4.Future<_i5.Result<int?, _i6.AppError>>.value(
              _i7.dummyValue<_i5.Result<int?, _i6.AppError>>(
                this,
                Invocation.method(#getLastImportTime, [profileId, dataType]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<int?, _i6.AppError>>);

  @override
  _i4.Future<_i5.Result<List<_i13.ImportedVital>, _i6.AppError>>
  getModifiedSince(int? since) =>
      (super.noSuchMethod(
            Invocation.method(#getModifiedSince, [since]),
            returnValue:
                _i4.Future<
                  _i5.Result<List<_i13.ImportedVital>, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i5.Result<List<_i13.ImportedVital>, _i6.AppError>
                  >(this, Invocation.method(#getModifiedSince, [since])),
                ),
          )
          as _i4.Future<_i5.Result<List<_i13.ImportedVital>, _i6.AppError>>);
}

/// A class which mocks [ProfileAuthorizationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileAuthorizationService extends _i1.Mock
    implements _i14.ProfileAuthorizationService {
  MockProfileAuthorizationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> canRead(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#canRead, [profileId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> canWrite(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#canWrite, [profileId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> isOwner(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#isOwner, [profileId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<_i14.ProfileAccess>> getAccessibleProfiles() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessibleProfiles, []),
            returnValue: _i4.Future<List<_i14.ProfileAccess>>.value(
              <_i14.ProfileAccess>[],
            ),
          )
          as _i4.Future<List<_i14.ProfileAccess>>);
}
