// Mocks generated by Mockito 5.4.6 from annotations
// in shadow_app/test/unit/domain/usecases/profiles/profile_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:shadow_app/core/errors/app_error.dart' as _i6;
import 'package:shadow_app/core/services/device_info_service.dart' as _i9;
import 'package:shadow_app/core/types/result.dart' as _i4;
import 'package:shadow_app/domain/entities/profile.dart' as _i5;
import 'package:shadow_app/domain/repositories/profile_repository.dart' as _i2;
import 'package:shadow_app/domain/services/profile_authorization_service.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i2.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.Profile>, _i6.AppError>> getByOwner(
    String? ownerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getByOwner, [ownerId]),
            returnValue:
                _i3.Future<_i4.Result<List<_i5.Profile>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i5.Profile>, _i6.AppError>>(
                    this,
                    Invocation.method(#getByOwner, [ownerId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.Profile>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i5.Profile?, _i6.AppError>> getDefault(
    String? ownerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDefault, [ownerId]),
            returnValue:
                _i3.Future<_i4.Result<_i5.Profile?, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i5.Profile?, _i6.AppError>>(
                    this,
                    Invocation.method(#getDefault, [ownerId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.Profile?, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Profile>, _i6.AppError>> getByUser(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getByUser, [userId]),
            returnValue:
                _i3.Future<_i4.Result<List<_i5.Profile>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i5.Profile>, _i6.AppError>>(
                    this,
                    Invocation.method(#getByUser, [userId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.Profile>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Profile>, _i6.AppError>> getAll({
    String? profileId,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {
              #profileId: profileId,
              #limit: limit,
              #offset: offset,
            }),
            returnValue:
                _i3.Future<_i4.Result<List<_i5.Profile>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i5.Profile>, _i6.AppError>>(
                    this,
                    Invocation.method(#getAll, [], {
                      #profileId: profileId,
                      #limit: limit,
                      #offset: offset,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.Profile>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i5.Profile, _i6.AppError>> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue:
                _i3.Future<_i4.Result<_i5.Profile, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i5.Profile, _i6.AppError>>(
                    this,
                    Invocation.method(#getById, [id]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.Profile, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i5.Profile, _i6.AppError>> create(
    _i5.Profile? entity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [entity]),
            returnValue:
                _i3.Future<_i4.Result<_i5.Profile, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i5.Profile, _i6.AppError>>(
                    this,
                    Invocation.method(#create, [entity]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.Profile, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i5.Profile, _i6.AppError>> update(
    _i5.Profile? entity, {
    bool? markDirty = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update, [entity], {#markDirty: markDirty}),
            returnValue:
                _i3.Future<_i4.Result<_i5.Profile, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i5.Profile, _i6.AppError>>(
                    this,
                    Invocation.method(
                      #update,
                      [entity],
                      {#markDirty: markDirty},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.Profile, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#delete, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> hardDelete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#hardDelete, [id]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#hardDelete, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Profile>, _i6.AppError>> getModifiedSince(
    int? since,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getModifiedSince, [since]),
            returnValue:
                _i3.Future<_i4.Result<List<_i5.Profile>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i5.Profile>, _i6.AppError>>(
                    this,
                    Invocation.method(#getModifiedSince, [since]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.Profile>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Profile>, _i6.AppError>> getPendingSync() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSync, []),
            returnValue:
                _i3.Future<_i4.Result<List<_i5.Profile>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i5.Profile>, _i6.AppError>>(
                    this,
                    Invocation.method(#getPendingSync, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.Profile>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> markSynced(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markSynced, [id]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#markSynced, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);
}

/// A class which mocks [ProfileAuthorizationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileAuthorizationService extends _i1.Mock
    implements _i8.ProfileAuthorizationService {
  MockProfileAuthorizationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> canRead(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#canRead, [profileId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> canWrite(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#canWrite, [profileId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> isOwner(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#isOwner, [profileId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i8.ProfileAccess>> getAccessibleProfiles() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessibleProfiles, []),
            returnValue: _i3.Future<List<_i8.ProfileAccess>>.value(
              <_i8.ProfileAccess>[],
            ),
          )
          as _i3.Future<List<_i8.ProfileAccess>>);
}

/// A class which mocks [DeviceInfoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceInfoService extends _i1.Mock implements _i9.DeviceInfoService {
  MockDeviceInfoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> getDeviceId() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceId, []),
            returnValue: _i3.Future<String>.value(
              _i7.dummyValue<String>(this, Invocation.method(#getDeviceId, [])),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> getDeviceName() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceName, []),
            returnValue: _i3.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getDeviceName, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  String getPlatform() =>
      (super.noSuchMethod(
            Invocation.method(#getPlatform, []),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#getPlatform, []),
            ),
          )
          as String);
}
