// Mocks generated by Mockito 5.4.6 from annotations
// in shadow_app/test/unit/presentation/providers/cloud_sync/cloud_sync_auth_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:shadow_app/core/errors/app_error.dart' as _i6;
import 'package:shadow_app/core/types/result.dart' as _i5;
import 'package:shadow_app/domain/services/cloud_sync_auth_service.dart' as _i2;
import 'package:shadow_app/domain/services/cloud_sync_auth_state.dart' as _i4;
import 'package:shadow_app/domain/sync/cloud_storage_provider.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CloudSyncAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCloudSyncAuthService extends _i1.Mock
    implements _i2.CloudSyncAuthService {
  MockCloudSyncAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.CloudSyncAuthState?> checkExistingSession() =>
      (super.noSuchMethod(
            Invocation.method(#checkExistingSession, []),
            returnValue: _i3.Future<_i4.CloudSyncAuthState?>.value(),
          )
          as _i3.Future<_i4.CloudSyncAuthState?>);

  @override
  _i3.Future<_i5.Result<_i4.CloudSyncAuthState, _i6.AppError>>
  signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue:
                _i3.Future<
                  _i5.Result<_i4.CloudSyncAuthState, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i5.Result<_i4.CloudSyncAuthState, _i6.AppError>
                  >(this, Invocation.method(#signInWithGoogle, [])),
                ),
          )
          as _i3.Future<_i5.Result<_i4.CloudSyncAuthState, _i6.AppError>>);

  @override
  _i3.Future<_i5.Result<_i4.CloudSyncAuthState, _i6.AppError>>
  signInWithICloud() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithICloud, []),
            returnValue:
                _i3.Future<
                  _i5.Result<_i4.CloudSyncAuthState, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i5.Result<_i4.CloudSyncAuthState, _i6.AppError>
                  >(this, Invocation.method(#signInWithICloud, [])),
                ),
          )
          as _i3.Future<_i5.Result<_i4.CloudSyncAuthState, _i6.AppError>>);

  @override
  _i3.Future<_i5.Result<_i4.CloudSyncAuthState, _i6.AppError>> switchProvider(
    _i8.CloudProviderType? type,
    _i8.CloudProviderType? currentProvider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#switchProvider, [type, currentProvider]),
            returnValue:
                _i3.Future<
                  _i5.Result<_i4.CloudSyncAuthState, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i5.Result<_i4.CloudSyncAuthState, _i6.AppError>
                  >(
                    this,
                    Invocation.method(#switchProvider, [type, currentProvider]),
                  ),
                ),
          )
          as _i3.Future<_i5.Result<_i4.CloudSyncAuthState, _i6.AppError>>);

  @override
  _i3.Future<_i5.Result<void, _i6.AppError>> signOut(
    _i8.CloudProviderType? activeProvider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [activeProvider]),
            returnValue: _i3.Future<_i5.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i5.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#signOut, [activeProvider]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void, _i6.AppError>>);
}
