// Mocks generated by Mockito 5.4.6 from annotations
// in shadow_app/test/unit/presentation/providers/cloud_sync/cloud_sync_auth_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:shadow_app/core/errors/app_error.dart' as _i6;
import 'package:shadow_app/core/types/result.dart' as _i5;
import 'package:shadow_app/data/cloud/google_drive_provider.dart' as _i2;
import 'package:shadow_app/data/datasources/remote/cloud_storage_provider.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GoogleDriveProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleDriveProvider extends _i1.Mock
    implements _i2.GoogleDriveProvider {
  MockGoogleDriveProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.CloudProviderType get providerType =>
      (super.noSuchMethod(
            Invocation.getter(#providerType),
            returnValue: _i3.CloudProviderType.googleDrive,
          )
          as _i3.CloudProviderType);

  @override
  _i4.Future<_i5.Result<void, _i6.AppError>> authenticate() =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, []),
            returnValue: _i4.Future<_i5.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i5.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#authenticate, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void, _i6.AppError>>);

  @override
  _i4.Future<_i5.Result<void, _i6.AppError>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<_i5.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i5.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void, _i6.AppError>>);

  @override
  _i4.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> isAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isAvailable, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i5.Result<void, _i6.AppError>> uploadEntity(
    String? entityType,
    String? entityId,
    String? profileId,
    String? clientId,
    Map<String, dynamic>? json,
    int? version,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadEntity, [
              entityType,
              entityId,
              profileId,
              clientId,
              json,
              version,
            ]),
            returnValue: _i4.Future<_i5.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i5.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#uploadEntity, [
                  entityType,
                  entityId,
                  profileId,
                  clientId,
                  json,
                  version,
                ]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void, _i6.AppError>>);

  @override
  _i4.Future<_i5.Result<Map<String, dynamic>?, _i6.AppError>> downloadEntity(
    String? entityType,
    String? entityId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#downloadEntity, [entityType, entityId]),
            returnValue:
                _i4.Future<
                  _i5.Result<Map<String, dynamic>?, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i5.Result<Map<String, dynamic>?, _i6.AppError>
                  >(
                    this,
                    Invocation.method(#downloadEntity, [entityType, entityId]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<Map<String, dynamic>?, _i6.AppError>>);

  @override
  _i4.Future<_i5.Result<List<_i3.SyncChange>, _i6.AppError>> getChangesSince(
    int? sinceTimestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getChangesSince, [sinceTimestamp]),
            returnValue:
                _i4.Future<
                  _i5.Result<List<_i3.SyncChange>, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i5.Result<List<_i3.SyncChange>, _i6.AppError>
                  >(
                    this,
                    Invocation.method(#getChangesSince, [sinceTimestamp]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<List<_i3.SyncChange>, _i6.AppError>>);

  @override
  _i4.Future<_i5.Result<void, _i6.AppError>> deleteEntity(
    String? entityType,
    String? entityId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEntity, [entityType, entityId]),
            returnValue: _i4.Future<_i5.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i5.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#deleteEntity, [entityType, entityId]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void, _i6.AppError>>);

  @override
  _i4.Future<_i5.Result<void, _i6.AppError>> uploadFile(
    String? localPath,
    String? remotePath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFile, [localPath, remotePath]),
            returnValue: _i4.Future<_i5.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i5.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#uploadFile, [localPath, remotePath]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void, _i6.AppError>>);

  @override
  _i4.Future<_i5.Result<String, _i6.AppError>> downloadFile(
    String? remotePath,
    String? localPath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#downloadFile, [remotePath, localPath]),
            returnValue: _i4.Future<_i5.Result<String, _i6.AppError>>.value(
              _i7.dummyValue<_i5.Result<String, _i6.AppError>>(
                this,
                Invocation.method(#downloadFile, [remotePath, localPath]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<String, _i6.AppError>>);
}
