// lib/presentation/screens/profiles/add_edit_profile_screen.dart
// Form for creating/editing profiles.

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shadow_app/presentation/providers/profile/profile_provider.dart';
import 'package:shadow_app/presentation/widgets/widgets.dart';

/// Screen for creating or editing a profile.
class AddEditProfileScreen extends ConsumerStatefulWidget {
  final Profile? profile;

  const AddEditProfileScreen({super.key, this.profile});

  @override
  ConsumerState<AddEditProfileScreen> createState() =>
      _AddEditProfileScreenState();
}

class _AddEditProfileScreenState extends ConsumerState<AddEditProfileScreen> {
  final _formKey = GlobalKey<FormState>();
  late final TextEditingController _nameController;
  late final TextEditingController _notesController;
  DateTime? _dateOfBirth;

  bool get _isEditing => widget.profile != null;

  @override
  void initState() {
    super.initState();
    _nameController = TextEditingController(text: widget.profile?.name ?? '');
    _notesController = TextEditingController(text: widget.profile?.notes ?? '');
    _dateOfBirth = widget.profile?.dateOfBirth;
  }

  @override
  void dispose() {
    _nameController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => Scaffold(
    appBar: AppBar(
      title: Text(_isEditing ? 'Edit Profile' : 'Create Profile'),
      backgroundColor: Colors.indigo,
      foregroundColor: Colors.white,
    ),
    body: Form(
      key: _formKey,
      child: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          TextFormField(
            controller: _nameController,
            decoration: const InputDecoration(
              labelText: 'Name',
              hintText: 'Enter your name',
              border: OutlineInputBorder(),
            ),
            validator: (value) {
              if (value == null || value.trim().isEmpty) {
                return 'Name is required';
              }
              return null;
            },
            autofocus: !_isEditing,
          ),
          const SizedBox(height: 16),
          ListTile(
            title: const Text('Date of Birth'),
            subtitle: Text(
              _dateOfBirth != null
                  ? '${_dateOfBirth!.month}/${_dateOfBirth!.day}/${_dateOfBirth!.year}'
                  : 'Not set',
            ),
            trailing: const Icon(Icons.calendar_today),
            onTap: _pickDateOfBirth,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8),
              side: BorderSide(color: Colors.grey[300]!),
            ),
          ),
          const SizedBox(height: 16),
          TextFormField(
            controller: _notesController,
            decoration: const InputDecoration(
              labelText: 'Notes',
              hintText: 'Optional notes',
              border: OutlineInputBorder(),
            ),
            maxLines: 3,
          ),
          const SizedBox(height: 32),
          SizedBox(
            width: double.infinity,
            child: ElevatedButton(
              onPressed: _save,
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.indigo,
                foregroundColor: Colors.white,
                padding: const EdgeInsets.all(16),
              ),
              child: Text(
                _isEditing ? 'Update Profile' : 'Create Profile',
                style: const TextStyle(fontSize: 16),
              ),
            ),
          ),
        ],
      ),
    ),
  );

  Future<void> _pickDateOfBirth() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _dateOfBirth ?? DateTime(1990),
      firstDate: DateTime(1900),
      lastDate: DateTime.now(),
    );
    if (picked != null) {
      setState(() => _dateOfBirth = picked);
    }
  }

  Future<void> _save() async {
    if (!_formKey.currentState!.validate()) return;

    final notifier = ref.read(profileProvider.notifier);

    if (_isEditing) {
      await notifier.updateProfile(
        widget.profile!.copyWith(
          name: _nameController.text.trim(),
          dateOfBirth: _dateOfBirth,
          notes: _notesController.text.trim(),
        ),
      );
    } else {
      await notifier.addProfile(
        Profile(
          id: '', // Will be generated by notifier
          name: _nameController.text.trim(),
          dateOfBirth: _dateOfBirth,
          notes: _notesController.text.trim(),
          createdAt: DateTime.now(),
        ),
      );
    }

    if (mounted) {
      showAccessibleSnackBar(
        context: context,
        message: _isEditing ? 'Profile updated' : 'Profile created',
      );
      Navigator.of(context).pop();
    }
  }
}
