// Mocks generated by Mockito 5.4.6 from annotations
// in shadow_app/test/unit/domain/usecases/food_logs/food_log_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:shadow_app/core/errors/app_error.dart' as _i6;
import 'package:shadow_app/core/types/result.dart' as _i4;
import 'package:shadow_app/domain/entities/food_item.dart' as _i9;
import 'package:shadow_app/domain/entities/food_item_component.dart' as _i11;
import 'package:shadow_app/domain/entities/food_log.dart' as _i5;
import 'package:shadow_app/domain/enums/health_enums.dart' as _i10;
import 'package:shadow_app/domain/repositories/food_item_repository.dart'
    as _i8;
import 'package:shadow_app/domain/repositories/food_log_repository.dart' as _i2;
import 'package:shadow_app/domain/services/profile_authorization_service.dart'
    as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FoodLogRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoodLogRepository extends _i1.Mock implements _i2.FoodLogRepository {
  MockFoodLogRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.FoodLog>, _i6.AppError>> getByProfile(
    String? profileId, {
    int? startDate,
    int? endDate,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getByProfile,
              [profileId],
              {
                #startDate: startDate,
                #endDate: endDate,
                #limit: limit,
                #offset: offset,
              },
            ),
            returnValue:
                _i3.Future<_i4.Result<List<_i5.FoodLog>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i5.FoodLog>, _i6.AppError>>(
                    this,
                    Invocation.method(
                      #getByProfile,
                      [profileId],
                      {
                        #startDate: startDate,
                        #endDate: endDate,
                        #limit: limit,
                        #offset: offset,
                      },
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.FoodLog>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i5.FoodLog>, _i6.AppError>> getForDate(
    String? profileId,
    int? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getForDate, [profileId, date]),
            returnValue:
                _i3.Future<_i4.Result<List<_i5.FoodLog>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i5.FoodLog>, _i6.AppError>>(
                    this,
                    Invocation.method(#getForDate, [profileId, date]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.FoodLog>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i5.FoodLog>, _i6.AppError>> getByDateRange(
    String? profileId,
    int? startDate,
    int? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getByDateRange, [profileId, startDate, endDate]),
            returnValue:
                _i3.Future<_i4.Result<List<_i5.FoodLog>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i5.FoodLog>, _i6.AppError>>(
                    this,
                    Invocation.method(#getByDateRange, [
                      profileId,
                      startDate,
                      endDate,
                    ]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.FoodLog>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i5.FoodLog>, _i6.AppError>> getAll({
    String? profileId,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {
              #profileId: profileId,
              #limit: limit,
              #offset: offset,
            }),
            returnValue:
                _i3.Future<_i4.Result<List<_i5.FoodLog>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i5.FoodLog>, _i6.AppError>>(
                    this,
                    Invocation.method(#getAll, [], {
                      #profileId: profileId,
                      #limit: limit,
                      #offset: offset,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.FoodLog>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i5.FoodLog, _i6.AppError>> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue:
                _i3.Future<_i4.Result<_i5.FoodLog, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i5.FoodLog, _i6.AppError>>(
                    this,
                    Invocation.method(#getById, [id]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.FoodLog, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i5.FoodLog, _i6.AppError>> create(
    _i5.FoodLog? entity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [entity]),
            returnValue:
                _i3.Future<_i4.Result<_i5.FoodLog, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i5.FoodLog, _i6.AppError>>(
                    this,
                    Invocation.method(#create, [entity]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.FoodLog, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i5.FoodLog, _i6.AppError>> update(
    _i5.FoodLog? entity, {
    bool? markDirty = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update, [entity], {#markDirty: markDirty}),
            returnValue:
                _i3.Future<_i4.Result<_i5.FoodLog, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i5.FoodLog, _i6.AppError>>(
                    this,
                    Invocation.method(
                      #update,
                      [entity],
                      {#markDirty: markDirty},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.FoodLog, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#delete, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> hardDelete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#hardDelete, [id]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#hardDelete, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i5.FoodLog>, _i6.AppError>> getModifiedSince(
    int? since,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getModifiedSince, [since]),
            returnValue:
                _i3.Future<_i4.Result<List<_i5.FoodLog>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i5.FoodLog>, _i6.AppError>>(
                    this,
                    Invocation.method(#getModifiedSince, [since]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.FoodLog>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i5.FoodLog>, _i6.AppError>> getPendingSync() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSync, []),
            returnValue:
                _i3.Future<_i4.Result<List<_i5.FoodLog>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i5.FoodLog>, _i6.AppError>>(
                    this,
                    Invocation.method(#getPendingSync, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.FoodLog>, _i6.AppError>>);
}

/// A class which mocks [FoodItemRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoodItemRepository extends _i1.Mock
    implements _i8.FoodItemRepository {
  MockFoodItemRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i9.FoodItem>, _i6.AppError>> getByProfile(
    String? profileId, {
    _i10.FoodItemType? type,
    bool? includeArchived = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getByProfile,
              [profileId],
              {#type: type, #includeArchived: includeArchived},
            ),
            returnValue:
                _i3.Future<_i4.Result<List<_i9.FoodItem>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i9.FoodItem>, _i6.AppError>>(
                    this,
                    Invocation.method(
                      #getByProfile,
                      [profileId],
                      {#type: type, #includeArchived: includeArchived},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i9.FoodItem>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i9.FoodItem>, _i6.AppError>> search(
    String? profileId,
    String? query, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#search, [profileId, query], {#limit: limit}),
            returnValue:
                _i3.Future<_i4.Result<List<_i9.FoodItem>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i9.FoodItem>, _i6.AppError>>(
                    this,
                    Invocation.method(
                      #search,
                      [profileId, query],
                      {#limit: limit},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i9.FoodItem>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> archive(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#archive, [id]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#archive, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i9.FoodItem>, _i6.AppError>>
  searchExcludingCategories(
    String? profileId,
    String? query, {
    required List<String>? excludeCategories,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchExcludingCategories,
              [profileId, query],
              {#excludeCategories: excludeCategories, #limit: limit},
            ),
            returnValue:
                _i3.Future<_i4.Result<List<_i9.FoodItem>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i9.FoodItem>, _i6.AppError>>(
                    this,
                    Invocation.method(
                      #searchExcludingCategories,
                      [profileId, query],
                      {#excludeCategories: excludeCategories, #limit: limit},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i9.FoodItem>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i11.FoodItemComponent>, _i6.AppError>>
  getComponents(String? composedFoodItemId) =>
      (super.noSuchMethod(
            Invocation.method(#getComponents, [composedFoodItemId]),
            returnValue:
                _i3.Future<
                  _i4.Result<List<_i11.FoodItemComponent>, _i6.AppError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<List<_i11.FoodItemComponent>, _i6.AppError>
                  >(
                    this,
                    Invocation.method(#getComponents, [composedFoodItemId]),
                  ),
                ),
          )
          as _i3.Future<
            _i4.Result<List<_i11.FoodItemComponent>, _i6.AppError>
          >);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> replaceComponents(
    String? composedFoodItemId,
    List<_i11.FoodItemComponent>? components,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#replaceComponents, [
              composedFoodItemId,
              components,
            ]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#replaceComponents, [
                  composedFoodItemId,
                  components,
                ]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> deleteComponents(
    String? composedFoodItemId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteComponents, [composedFoodItemId]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#deleteComponents, [composedFoodItemId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i9.FoodItem>, _i6.AppError>> getAll({
    String? profileId,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {
              #profileId: profileId,
              #limit: limit,
              #offset: offset,
            }),
            returnValue:
                _i3.Future<_i4.Result<List<_i9.FoodItem>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i9.FoodItem>, _i6.AppError>>(
                    this,
                    Invocation.method(#getAll, [], {
                      #profileId: profileId,
                      #limit: limit,
                      #offset: offset,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i9.FoodItem>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i9.FoodItem, _i6.AppError>> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue:
                _i3.Future<_i4.Result<_i9.FoodItem, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i9.FoodItem, _i6.AppError>>(
                    this,
                    Invocation.method(#getById, [id]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i9.FoodItem, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i9.FoodItem, _i6.AppError>> create(
    _i9.FoodItem? entity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [entity]),
            returnValue:
                _i3.Future<_i4.Result<_i9.FoodItem, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i9.FoodItem, _i6.AppError>>(
                    this,
                    Invocation.method(#create, [entity]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i9.FoodItem, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<_i9.FoodItem, _i6.AppError>> update(
    _i9.FoodItem? entity, {
    bool? markDirty = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update, [entity], {#markDirty: markDirty}),
            returnValue:
                _i3.Future<_i4.Result<_i9.FoodItem, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<_i9.FoodItem, _i6.AppError>>(
                    this,
                    Invocation.method(
                      #update,
                      [entity],
                      {#markDirty: markDirty},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i9.FoodItem, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#delete, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.AppError>> hardDelete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#hardDelete, [id]),
            returnValue: _i3.Future<_i4.Result<void, _i6.AppError>>.value(
              _i7.dummyValue<_i4.Result<void, _i6.AppError>>(
                this,
                Invocation.method(#hardDelete, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i9.FoodItem>, _i6.AppError>> getModifiedSince(
    int? since,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getModifiedSince, [since]),
            returnValue:
                _i3.Future<_i4.Result<List<_i9.FoodItem>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i9.FoodItem>, _i6.AppError>>(
                    this,
                    Invocation.method(#getModifiedSince, [since]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i9.FoodItem>, _i6.AppError>>);

  @override
  _i3.Future<_i4.Result<List<_i9.FoodItem>, _i6.AppError>> getPendingSync() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSync, []),
            returnValue:
                _i3.Future<_i4.Result<List<_i9.FoodItem>, _i6.AppError>>.value(
                  _i7.dummyValue<_i4.Result<List<_i9.FoodItem>, _i6.AppError>>(
                    this,
                    Invocation.method(#getPendingSync, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i9.FoodItem>, _i6.AppError>>);
}

/// A class which mocks [ProfileAuthorizationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileAuthorizationService extends _i1.Mock
    implements _i12.ProfileAuthorizationService {
  MockProfileAuthorizationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> canRead(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#canRead, [profileId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> canWrite(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#canWrite, [profileId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> isOwner(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#isOwner, [profileId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i12.ProfileAccess>> getAccessibleProfiles() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessibleProfiles, []),
            returnValue: _i3.Future<List<_i12.ProfileAccess>>.value(
              <_i12.ProfileAccess>[],
            ),
          )
          as _i3.Future<List<_i12.ProfileAccess>>);
}
